// <auto-generated />
using System;
using FloristeriaWeb.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloristeriaWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505080148_NuevoCampoAspUsers")]
    partial class NuevoCampoAspUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloristeriaWeb.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Boaco"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Carazo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Chinandega"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Chontales"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Estelí"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Granada"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Jinotega"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "León"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Madriz"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Managua"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Masaya"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Matagalpa"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Nueva Segovia"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Río San Juan"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Rivas"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Costa Caribe Norte"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Costa Caribe Sur"
                        });
                });

            modelBuilder.Entity("FloristeriaWeb.Models.DetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FlorId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FlorId");

                    b.HasIndex("OrdenId");

                    b.ToTable("DetalleOrden");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Estado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Aprobado"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Rechazado"
                        });
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Flor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Flor");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            Nombre = "Boaco"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 1,
                            Nombre = "Camoapa"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 1,
                            Nombre = "San José de los Remates"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 1,
                            Nombre = "San Lorenzo"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 1,
                            Nombre = "Santa Lucía"
                        },
                        new
                        {
                            Id = 6,
                            DepartamentoId = 1,
                            Nombre = "Teustepe"
                        },
                        new
                        {
                            Id = 7,
                            DepartamentoId = 2,
                            Nombre = "Jinotepe"
                        },
                        new
                        {
                            Id = 8,
                            DepartamentoId = 2,
                            Nombre = "Diriamba"
                        },
                        new
                        {
                            Id = 9,
                            DepartamentoId = 2,
                            Nombre = "San Marcos"
                        },
                        new
                        {
                            Id = 10,
                            DepartamentoId = 2,
                            Nombre = "Dolores"
                        },
                        new
                        {
                            Id = 11,
                            DepartamentoId = 2,
                            Nombre = "Santa Teresa"
                        },
                        new
                        {
                            Id = 12,
                            DepartamentoId = 2,
                            Nombre = "El Rosario"
                        },
                        new
                        {
                            Id = 13,
                            DepartamentoId = 2,
                            Nombre = "La Paz de Carazo"
                        },
                        new
                        {
                            Id = 14,
                            DepartamentoId = 2,
                            Nombre = "La Conquista"
                        },
                        new
                        {
                            Id = 15,
                            DepartamentoId = 3,
                            Nombre = "Chinandega"
                        },
                        new
                        {
                            Id = 16,
                            DepartamentoId = 3,
                            Nombre = "El Viejo"
                        },
                        new
                        {
                            Id = 17,
                            DepartamentoId = 3,
                            Nombre = "Corinto"
                        },
                        new
                        {
                            Id = 18,
                            DepartamentoId = 3,
                            Nombre = "Chichigalpa"
                        },
                        new
                        {
                            Id = 19,
                            DepartamentoId = 3,
                            Nombre = "El Realejo"
                        },
                        new
                        {
                            Id = 20,
                            DepartamentoId = 3,
                            Nombre = "Posoltega"
                        },
                        new
                        {
                            Id = 21,
                            DepartamentoId = 3,
                            Nombre = "Quezalguaque"
                        },
                        new
                        {
                            Id = 22,
                            DepartamentoId = 3,
                            Nombre = "Somotillo"
                        },
                        new
                        {
                            Id = 23,
                            DepartamentoId = 3,
                            Nombre = "Villanueva"
                        },
                        new
                        {
                            Id = 24,
                            DepartamentoId = 3,
                            Nombre = "Santo Tomás del Norte"
                        },
                        new
                        {
                            Id = 25,
                            DepartamentoId = 3,
                            Nombre = "Cinco Pinos"
                        },
                        new
                        {
                            Id = 26,
                            DepartamentoId = 3,
                            Nombre = "San Pedro del Norte"
                        },
                        new
                        {
                            Id = 27,
                            DepartamentoId = 3,
                            Nombre = "San Francisco del Norte"
                        },
                        new
                        {
                            Id = 28,
                            DepartamentoId = 4,
                            Nombre = "Juigalpa"
                        },
                        new
                        {
                            Id = 29,
                            DepartamentoId = 4,
                            Nombre = "Acoyapa"
                        },
                        new
                        {
                            Id = 30,
                            DepartamentoId = 4,
                            Nombre = "Santo Tomás"
                        },
                        new
                        {
                            Id = 31,
                            DepartamentoId = 4,
                            Nombre = "La Libertad"
                        },
                        new
                        {
                            Id = 32,
                            DepartamentoId = 4,
                            Nombre = "San Pedro de Lóvago"
                        },
                        new
                        {
                            Id = 33,
                            DepartamentoId = 4,
                            Nombre = "Santo Domingo"
                        },
                        new
                        {
                            Id = 34,
                            DepartamentoId = 4,
                            Nombre = "Villa Sandino"
                        },
                        new
                        {
                            Id = 35,
                            DepartamentoId = 4,
                            Nombre = "Comalapa"
                        },
                        new
                        {
                            Id = 36,
                            DepartamentoId = 4,
                            Nombre = "San Francisco de Cuapa"
                        },
                        new
                        {
                            Id = 37,
                            DepartamentoId = 4,
                            Nombre = "El Coral"
                        },
                        new
                        {
                            Id = 38,
                            DepartamentoId = 5,
                            Nombre = "Estelí"
                        },
                        new
                        {
                            Id = 39,
                            DepartamentoId = 5,
                            Nombre = "Condega"
                        },
                        new
                        {
                            Id = 40,
                            DepartamentoId = 5,
                            Nombre = "Pueblo Nuevo"
                        },
                        new
                        {
                            Id = 41,
                            DepartamentoId = 5,
                            Nombre = "La Trinidad"
                        },
                        new
                        {
                            Id = 42,
                            DepartamentoId = 5,
                            Nombre = "San Juan de Limay"
                        },
                        new
                        {
                            Id = 43,
                            DepartamentoId = 5,
                            Nombre = "San Nicolás"
                        },
                        new
                        {
                            Id = 44,
                            DepartamentoId = 6,
                            Nombre = "Granada"
                        },
                        new
                        {
                            Id = 45,
                            DepartamentoId = 6,
                            Nombre = "Diriá"
                        },
                        new
                        {
                            Id = 46,
                            DepartamentoId = 6,
                            Nombre = "Diriomo"
                        },
                        new
                        {
                            Id = 47,
                            DepartamentoId = 6,
                            Nombre = "Nandaime"
                        },
                        new
                        {
                            Id = 48,
                            DepartamentoId = 7,
                            Nombre = "Jinotega"
                        },
                        new
                        {
                            Id = 49,
                            DepartamentoId = 7,
                            Nombre = "Wiwilí de Jinotega"
                        },
                        new
                        {
                            Id = 50,
                            DepartamentoId = 7,
                            Nombre = "El Cuá"
                        },
                        new
                        {
                            Id = 51,
                            DepartamentoId = 7,
                            Nombre = "San José de Bocay"
                        },
                        new
                        {
                            Id = 52,
                            DepartamentoId = 7,
                            Nombre = "San Sebastián de Yalí"
                        },
                        new
                        {
                            Id = 53,
                            DepartamentoId = 7,
                            Nombre = "Santa María de Pantasma"
                        },
                        new
                        {
                            Id = 54,
                            DepartamentoId = 7,
                            Nombre = "San Rafael del Norte"
                        },
                        new
                        {
                            Id = 55,
                            DepartamentoId = 7,
                            Nombre = "La Concordia"
                        },
                        new
                        {
                            Id = 56,
                            DepartamentoId = 8,
                            Nombre = "León"
                        },
                        new
                        {
                            Id = 57,
                            DepartamentoId = 8,
                            Nombre = "Nagarote"
                        },
                        new
                        {
                            Id = 58,
                            DepartamentoId = 8,
                            Nombre = "La Paz Centro"
                        },
                        new
                        {
                            Id = 59,
                            DepartamentoId = 8,
                            Nombre = "Telica"
                        },
                        new
                        {
                            Id = 60,
                            DepartamentoId = 8,
                            Nombre = "Quezalguaque"
                        },
                        new
                        {
                            Id = 61,
                            DepartamentoId = 8,
                            Nombre = "Larreynaga"
                        },
                        new
                        {
                            Id = 62,
                            DepartamentoId = 8,
                            Nombre = "El Sauce"
                        },
                        new
                        {
                            Id = 63,
                            DepartamentoId = 8,
                            Nombre = "Achuapa"
                        },
                        new
                        {
                            Id = 64,
                            DepartamentoId = 8,
                            Nombre = "Santa Rosa del Peñón"
                        },
                        new
                        {
                            Id = 65,
                            DepartamentoId = 8,
                            Nombre = "El Jicaral"
                        },
                        new
                        {
                            Id = 66,
                            DepartamentoId = 9,
                            Nombre = "Somoto"
                        },
                        new
                        {
                            Id = 67,
                            DepartamentoId = 9,
                            Nombre = "Totogalpa"
                        },
                        new
                        {
                            Id = 68,
                            DepartamentoId = 9,
                            Nombre = "Telpaneca"
                        },
                        new
                        {
                            Id = 69,
                            DepartamentoId = 9,
                            Nombre = "San Lucas"
                        },
                        new
                        {
                            Id = 70,
                            DepartamentoId = 9,
                            Nombre = "Yalagüina"
                        },
                        new
                        {
                            Id = 71,
                            DepartamentoId = 9,
                            Nombre = "Palacagüina"
                        },
                        new
                        {
                            Id = 72,
                            DepartamentoId = 9,
                            Nombre = "San Juan de Río Coco"
                        },
                        new
                        {
                            Id = 73,
                            DepartamentoId = 9,
                            Nombre = "San José de Cusmapa"
                        },
                        new
                        {
                            Id = 74,
                            DepartamentoId = 9,
                            Nombre = "Las Sabanas"
                        },
                        new
                        {
                            Id = 75,
                            DepartamentoId = 10,
                            Nombre = "Managua"
                        },
                        new
                        {
                            Id = 76,
                            DepartamentoId = 10,
                            Nombre = "Tipitapa"
                        },
                        new
                        {
                            Id = 77,
                            DepartamentoId = 10,
                            Nombre = "Ciudad Sandino"
                        },
                        new
                        {
                            Id = 78,
                            DepartamentoId = 10,
                            Nombre = "San Rafael del Sur"
                        },
                        new
                        {
                            Id = 79,
                            DepartamentoId = 10,
                            Nombre = "Mateare"
                        },
                        new
                        {
                            Id = 80,
                            DepartamentoId = 10,
                            Nombre = "Villa El Carmen"
                        },
                        new
                        {
                            Id = 81,
                            DepartamentoId = 10,
                            Nombre = "Ticuantepe"
                        },
                        new
                        {
                            Id = 82,
                            DepartamentoId = 10,
                            Nombre = "San Francisco Libre"
                        },
                        new
                        {
                            Id = 83,
                            DepartamentoId = 10,
                            Nombre = "El Crucero"
                        },
                        new
                        {
                            Id = 84,
                            DepartamentoId = 11,
                            Nombre = "Masaya"
                        },
                        new
                        {
                            Id = 85,
                            DepartamentoId = 11,
                            Nombre = "Nindirí"
                        },
                        new
                        {
                            Id = 86,
                            DepartamentoId = 11,
                            Nombre = "Masatepe"
                        },
                        new
                        {
                            Id = 87,
                            DepartamentoId = 11,
                            Nombre = "Nandasmo"
                        },
                        new
                        {
                            Id = 88,
                            DepartamentoId = 11,
                            Nombre = "Catarina"
                        },
                        new
                        {
                            Id = 89,
                            DepartamentoId = 11,
                            Nombre = "San Juan de Oriente"
                        },
                        new
                        {
                            Id = 90,
                            DepartamentoId = 11,
                            Nombre = "Niquinohomo"
                        },
                        new
                        {
                            Id = 91,
                            DepartamentoId = 11,
                            Nombre = "Tisma"
                        },
                        new
                        {
                            Id = 92,
                            DepartamentoId = 11,
                            Nombre = "La Concepción"
                        },
                        new
                        {
                            Id = 93,
                            DepartamentoId = 12,
                            Nombre = "Matagalpa"
                        },
                        new
                        {
                            Id = 94,
                            DepartamentoId = 12,
                            Nombre = "Sébaco"
                        },
                        new
                        {
                            Id = 95,
                            DepartamentoId = 12,
                            Nombre = "San Isidro"
                        },
                        new
                        {
                            Id = 96,
                            DepartamentoId = 12,
                            Nombre = "Ciudad Darío"
                        },
                        new
                        {
                            Id = 97,
                            DepartamentoId = 12,
                            Nombre = "Terrabona"
                        },
                        new
                        {
                            Id = 98,
                            DepartamentoId = 12,
                            Nombre = "San Dionisio"
                        },
                        new
                        {
                            Id = 99,
                            DepartamentoId = 12,
                            Nombre = "Esquipulas"
                        },
                        new
                        {
                            Id = 100,
                            DepartamentoId = 12,
                            Nombre = "Muy Muy"
                        },
                        new
                        {
                            Id = 101,
                            DepartamentoId = 12,
                            Nombre = "Matiguás"
                        },
                        new
                        {
                            Id = 102,
                            DepartamentoId = 12,
                            Nombre = "Río Blanco"
                        },
                        new
                        {
                            Id = 103,
                            DepartamentoId = 12,
                            Nombre = "San Ramón"
                        },
                        new
                        {
                            Id = 104,
                            DepartamentoId = 12,
                            Nombre = "Rancho Grande"
                        },
                        new
                        {
                            Id = 105,
                            DepartamentoId = 12,
                            Nombre = "Tuma-La Dalia"
                        },
                        new
                        {
                            Id = 106,
                            DepartamentoId = 13,
                            Nombre = "Ocotal"
                        },
                        new
                        {
                            Id = 107,
                            DepartamentoId = 13,
                            Nombre = "Jalapa"
                        },
                        new
                        {
                            Id = 108,
                            DepartamentoId = 13,
                            Nombre = "Wiwilí de Nueva Segovia"
                        },
                        new
                        {
                            Id = 109,
                            DepartamentoId = 13,
                            Nombre = "Quilalí"
                        },
                        new
                        {
                            Id = 110,
                            DepartamentoId = 13,
                            Nombre = "Jícaro"
                        },
                        new
                        {
                            Id = 111,
                            DepartamentoId = 13,
                            Nombre = "Murra"
                        },
                        new
                        {
                            Id = 112,
                            DepartamentoId = 13,
                            Nombre = "San Fernando"
                        },
                        new
                        {
                            Id = 113,
                            DepartamentoId = 13,
                            Nombre = "Ciudad Antigua"
                        },
                        new
                        {
                            Id = 114,
                            DepartamentoId = 13,
                            Nombre = "Mozonte"
                        },
                        new
                        {
                            Id = 115,
                            DepartamentoId = 13,
                            Nombre = "Dipilto"
                        },
                        new
                        {
                            Id = 116,
                            DepartamentoId = 13,
                            Nombre = "Santa María"
                        },
                        new
                        {
                            Id = 117,
                            DepartamentoId = 13,
                            Nombre = "Macuelizo"
                        },
                        new
                        {
                            Id = 118,
                            DepartamentoId = 14,
                            Nombre = "San Carlos"
                        },
                        new
                        {
                            Id = 119,
                            DepartamentoId = 14,
                            Nombre = "El Castillo"
                        },
                        new
                        {
                            Id = 120,
                            DepartamentoId = 14,
                            Nombre = "San Juan del Norte"
                        },
                        new
                        {
                            Id = 121,
                            DepartamentoId = 14,
                            Nombre = "San Miguelito"
                        },
                        new
                        {
                            Id = 122,
                            DepartamentoId = 14,
                            Nombre = "El Almendro"
                        },
                        new
                        {
                            Id = 123,
                            DepartamentoId = 14,
                            Nombre = "Morrito"
                        },
                        new
                        {
                            Id = 124,
                            DepartamentoId = 15,
                            Nombre = "Rivas"
                        },
                        new
                        {
                            Id = 125,
                            DepartamentoId = 15,
                            Nombre = "San Juan del Sur"
                        },
                        new
                        {
                            Id = 126,
                            DepartamentoId = 15,
                            Nombre = "Moyogalpa"
                        },
                        new
                        {
                            Id = 127,
                            DepartamentoId = 15,
                            Nombre = "Altagracia"
                        },
                        new
                        {
                            Id = 128,
                            DepartamentoId = 15,
                            Nombre = "Tola"
                        },
                        new
                        {
                            Id = 129,
                            DepartamentoId = 15,
                            Nombre = "San Jorge"
                        },
                        new
                        {
                            Id = 130,
                            DepartamentoId = 15,
                            Nombre = "Potosí"
                        },
                        new
                        {
                            Id = 131,
                            DepartamentoId = 15,
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = 132,
                            DepartamentoId = 15,
                            Nombre = "Belén"
                        },
                        new
                        {
                            Id = 133,
                            DepartamentoId = 15,
                            Nombre = "Cárdenas"
                        },
                        new
                        {
                            Id = 134,
                            DepartamentoId = 16,
                            Nombre = "Puerto Cabezas"
                        },
                        new
                        {
                            Id = 135,
                            DepartamentoId = 16,
                            Nombre = "Waspam"
                        },
                        new
                        {
                            Id = 136,
                            DepartamentoId = 16,
                            Nombre = "Siuna"
                        },
                        new
                        {
                            Id = 137,
                            DepartamentoId = 16,
                            Nombre = "Rosita"
                        },
                        new
                        {
                            Id = 138,
                            DepartamentoId = 16,
                            Nombre = "Bonanza"
                        },
                        new
                        {
                            Id = 139,
                            DepartamentoId = 16,
                            Nombre = "Prinzapolka"
                        },
                        new
                        {
                            Id = 140,
                            DepartamentoId = 16,
                            Nombre = "Waslala"
                        },
                        new
                        {
                            Id = 141,
                            DepartamentoId = 16,
                            Nombre = "Mulukukú"
                        },
                        new
                        {
                            Id = 142,
                            DepartamentoId = 17,
                            Nombre = "Bluefields"
                        },
                        new
                        {
                            Id = 143,
                            DepartamentoId = 17,
                            Nombre = "Corn Island"
                        },
                        new
                        {
                            Id = 144,
                            DepartamentoId = 17,
                            Nombre = "Laguna de Perlas"
                        },
                        new
                        {
                            Id = 145,
                            DepartamentoId = 17,
                            Nombre = "Nueva Guinea"
                        },
                        new
                        {
                            Id = 146,
                            DepartamentoId = 17,
                            Nombre = "El Rama"
                        },
                        new
                        {
                            Id = 147,
                            DepartamentoId = 17,
                            Nombre = "Kukra Hill"
                        },
                        new
                        {
                            Id = 148,
                            DepartamentoId = 17,
                            Nombre = "La Cruz de Río Grande"
                        },
                        new
                        {
                            Id = 149,
                            DepartamentoId = 17,
                            Nombre = "Desembocadura de Río Grande"
                        },
                        new
                        {
                            Id = 150,
                            DepartamentoId = 17,
                            Nombre = "El Tortuguero"
                        },
                        new
                        {
                            Id = 151,
                            DepartamentoId = 17,
                            Nombre = "Muelle de los Bueyes"
                        },
                        new
                        {
                            Id = 152,
                            DepartamentoId = 17,
                            Nombre = "El Ayote"
                        },
                        new
                        {
                            Id = 153,
                            DepartamentoId = 17,
                            Nombre = "Paiwas"
                        });
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoDestinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("EstadoPagoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPagoId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.UsuarioAplicacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FloristeriaWeb.Models.DetalleOrden", b =>
                {
                    b.HasOne("FloristeriaWeb.Models.Flor", "Flor")
                        .WithMany("Detalles")
                        .HasForeignKey("FlorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloristeriaWeb.Models.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flor");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Flor", b =>
                {
                    b.HasOne("FloristeriaWeb.Models.Categoria", "Categoria")
                        .WithMany("Flores")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Municipio", b =>
                {
                    b.HasOne("FloristeriaWeb.Models.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Orden", b =>
                {
                    b.HasOne("FloristeriaWeb.Models.Estado", "Estado")
                        .WithMany("Ordenes")
                        .HasForeignKey("EstadoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloristeriaWeb.Models.Municipio", "Municipio")
                        .WithMany("Ordenes")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FloristeriaWeb.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FloristeriaWeb.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloristeriaWeb.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FloristeriaWeb.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Categoria", b =>
                {
                    b.Navigation("Flores");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Estado", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Flor", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Municipio", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("FloristeriaWeb.Models.Orden", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
